name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      run:
        docker login -u $username -p $password
    - name: Build the Docker image
      run: docker build . --file action-a/Dockerfile --tag yxnn14/repojean:latest
    - name: Docker Push
      run: sudo docker push yxnn14/repojean:latest
