name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    env:
        tag : ${{ secrets.DOCKERHUB_USERNAME }}/repojean:$(date +%s)
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      
      run:
        docker login -u $username -p $password
    - name: Build the Docker image
       
      run: docker build . --file action-a/Dockerfile --tag echo ${{ tag }}
    - name: Docker Push
      run: docker push ${{ env.tag }}
